import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import Providers from "./Providers";
import MenuBar from "./MenuBar";
import Footer from "./Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <MenuBar />
                    {children}
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
